Fixed some comparison errors for Jacobian functions
auto-differentiation/xad pull request #146
Opened 2024-11-17 13:04 UTC by raneamri

## Type of change

Simple recast on some comparisons that triggered warnings with MSVC2022.

-   Bug fix (non-breaking change which fixes an issue)

2024-11-17 14:11 UTC, xcelerit-team requested changes
Thanks for that. 

Could you use `std::size_t` for the type instead? This is also the type used for the `size_type` of STL containers.

2024-11-18 13:16 UTC, auto-differentiation-dev requested changes
Just a few simplifications, then it's good to go

2024-11-18 13:16 UTC, auto-differentiation-dev commented on src/XAD/Hessian.hpp
> +    std::size_t domain(static_cast<std::size_t>(vec.size()));
```suggestion
    std::size_t domain = vec.size();
```

2024-11-18 13:16 UTC, auto-differentiation-dev commented on src/XAD/Hessian.hpp
> +    std::size_t domain(static_cast<std::size_t>(vec.size()));
```suggestion
    std::size_t domain = vec.size();
```

2024-11-18 13:16 UTC, auto-differentiation-dev commented on src/XAD/Jacobian.hpp
> +                 codomain = static_cast<std::size_t>(y.size());
```suggestion
    std::size_t domain = vec.size();
    std::size_t codomain = y.size();
```

2024-11-18 13:19 UTC, xcelerit-team approved these changes

2024-11-18 18:48 UTC, merged